//! systemd implementation of [`ServiceManager`]: unit `asc.service`.

use std::fs;
use std::io;
use std::path::Path;
use std::process::Command;

use anyhow::{Context, Result, bail};

use super::{ServiceManager, ServiceState};

/// systemd unit name of the daemon.
pub const UNIT_NAME: &str = "asc";
const UNIT_PATH: &str = "/etc/systemd/system/asc.service";

/// Whether systemd is present on this host.
pub fn available() -> bool {
    Command::new("systemctl")
        .arg("--version")
        .output()
        .is_ok_and(|out| out.status.success())
}

pub struct Systemd;

impl Systemd {
    fn unit_file(exec_path: &Path) -> String {
        format!(
            r#"# Generated by `asc service install` — manual edits will be overwritten.
[Unit]
Description=AdminService.Cloud daemon (asc)
Documentation=https://github.com/AdminServiceCloud/asc-daemon
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart={exec} serve
Restart=on-failure
RestartSec=5
LimitNOFILE=65535

[Install]
WantedBy=multi-user.target
"#,
            exec = exec_path.display()
        )
    }
}

impl ServiceManager for Systemd {
    fn install(&self) -> Result<()> {
        // Point the unit at the binary that is running right now, so a
        // non-standard install location keeps working.
        let exec_path = std::env::current_exe().context("cannot resolve current executable")?;
        fs::write(UNIT_PATH, Self::unit_file(&exec_path))
            .with_context(|| format!("cannot write systemd unit {UNIT_PATH}"))?;
        systemctl(&["daemon-reload"])?;
        systemctl(&["enable", UNIT_NAME])?;
        Ok(())
    }

    fn uninstall(&self) -> Result<()> {
        // Best effort: the unit may be stopped or disabled already.
        let _ = systemctl(&["disable", "--now", UNIT_NAME]);
        match fs::remove_file(UNIT_PATH) {
            Ok(()) => {}
            Err(e) if e.kind() == io::ErrorKind::NotFound => {}
            Err(e) => {
                return Err(e).with_context(|| format!("cannot remove systemd unit {UNIT_PATH}"));
            }
        }
        systemctl(&["daemon-reload"])?;
        Ok(())
    }

    fn start(&self) -> Result<()> {
        systemctl(&["start", UNIT_NAME])
    }

    fn stop(&self) -> Result<()> {
        systemctl(&["stop", UNIT_NAME])
    }

    fn restart(&self) -> Result<()> {
        systemctl(&["restart", UNIT_NAME])
    }

    fn state(&self) -> Result<ServiceState> {
        if !Path::new(UNIT_PATH).exists() {
            return Ok(ServiceState::NotInstalled);
        }
        let out = Command::new("systemctl")
            .args(["is-active", UNIT_NAME])
            .output()
            .context("cannot run systemctl")?;
        let state = String::from_utf8_lossy(&out.stdout);
        match state.trim() {
            "active" | "activating" => Ok(ServiceState::Active),
            _ => Ok(ServiceState::Inactive),
        }
    }
}

pub(crate) fn systemctl(args: &[&str]) -> Result<()> {
    let out = Command::new("systemctl")
        .args(args)
        .output()
        .context("cannot run systemctl")?;
    if !out.status.success() {
        bail!(
            "systemctl {} failed: {}",
            args.join(" "),
            String::from_utf8_lossy(&out.stderr).trim()
        );
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn unit_file_points_exec_start_at_binary() {
        let unit = Systemd::unit_file(Path::new("/usr/local/bin/asc"));
        assert!(unit.contains("ExecStart=/usr/local/bin/asc serve"));
        assert!(unit.contains("WantedBy=multi-user.target"));
    }
}
