//! nginx configuration rendering (DMN-122/DMN-123). Pure functions: the
//! caller resolves upstreams and certificate paths, this module only turns
//! settings and sites into file contents. Every path a rendered file refers
//! to is built from `base`, so the same code renders both the staging copy
//! `nginx -t` checks and the live files.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use super::cloudflare::Ranges;
use super::model::{Balance, RealIp, Settings, Site};

/// Where the web server's files live.
#[derive(Debug, Clone)]
pub struct Paths {
    /// Generated configuration: `/etc/asc/webserver`.
    pub root: PathBuf,
    /// Daemon state: `/var/lib/asc/webserver` (sites, statuses, ACME).
    pub state: PathBuf,
    /// HTTP-01 webroot, readable by the nginx worker user.
    pub webroot: PathBuf,
}

impl Paths {
    pub fn system() -> Self {
        Self {
            root: PathBuf::from("/etc/asc/webserver"),
            state: PathBuf::from("/var/lib/asc/webserver"),
            webroot: PathBuf::from("/var/www/asc-acme"),
        }
    }

    pub fn staging(&self) -> PathBuf {
        self.root.join(".staging")
    }

    /// Certificates Let's Encrypt issued for a site.
    pub fn acme_cert_dir(&self, site: &str) -> PathBuf {
        self.state.join("acme").join("certs").join(site)
    }
}

/// Version-dependent syntax.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Features {
    /// `http2 on;` (1.25.1+) instead of `listen … http2`.
    pub http2_directive: bool,
    /// `ssl_reject_handshake` (1.19.4+).
    pub reject_handshake: bool,
    /// The host has IPv6 — `listen [::]:…` fails to bind otherwise.
    pub ipv6: bool,
}

impl Features {
    pub fn for_version(version: Option<&str>, ipv6: bool) -> Self {
        let parsed = version.and_then(parse_version);
        let at_least = |want: (u32, u32, u32)| parsed.is_none_or(|v| v >= want);
        Self {
            http2_directive: at_least((1, 25, 1)),
            reject_handshake: at_least((1, 19, 4)),
            ipv6,
        }
    }
}

pub fn parse_version(version: &str) -> Option<(u32, u32, u32)> {
    let mut parts = version.trim().split('.').map(|p| p.parse::<u32>().ok());
    Some((
        parts.next()??,
        parts.next()??,
        parts.next().flatten().unwrap_or(0),
    ))
}

/// A site ready to render: upstream addresses resolved, certificate located.
#[derive(Debug, Clone)]
pub struct Resolved<'a> {
    pub site: &'a Site,
    /// One per `site.upstream.servers`, same order.
    pub addresses: Vec<String>,
    /// Certificate and key to serve HTTPS with; `None` — HTTP only for now
    /// (no TLS, or the certificate is not issued yet).
    pub cert: Option<(PathBuf, PathBuf)>,
    /// Per server: taken out of rotation by the health checks (DMN-126).
    pub down: Vec<bool>,
}

/// Relative path (under `base`) → file content.
pub type Files = BTreeMap<PathBuf, String>;

pub const NGINX_CONF: &str = "nginx.conf";
pub const CUSTOM_HTTP: &str = "http.d/custom.conf";
pub const CLOUDFLARE: &str = "snippets/cloudflare-realip.conf";
pub const ACME_SNIPPET: &str = "snippets/acme.conf";
pub const PROXY_SNIPPET: &str = "snippets/proxy.conf";

pub fn site_file(id: &str) -> PathBuf {
    PathBuf::from("sites").join(format!("{id}.conf"))
}

pub fn provided_cert_files(id: &str) -> (PathBuf, PathBuf) {
    let dir = PathBuf::from("certs").join(id);
    (dir.join("fullchain.pem"), dir.join("privkey.pem"))
}

const HEADER: &str = "# Generated by asc-daemon. Change it with `asc web` or in the AdminService.Cloud\n\
# panel — manual edits are overwritten on the next apply.\n";

fn p(base: &Path, rel: &str) -> String {
    base.join(rel).display().to_string()
}

fn indent(text: &str, by: &str) -> String {
    text.lines()
        .map(|l| {
            if l.trim().is_empty() {
                String::new()
            } else {
                format!("{by}{l}")
            }
        })
        .collect::<Vec<_>>()
        .join("\n")
}

/// Everything node-wide: `nginx.conf` and the shared snippets.
pub fn render_global(
    settings: &Settings,
    features: Features,
    cloudflare: &Ranges,
    paths: &Paths,
    base: &Path,
    docker: bool,
) -> Files {
    let mut files = Files::new();
    let host = &settings.host;
    let mut c = String::from(HEADER);
    let user = if docker || host.user.is_empty() {
        "nginx"
    } else {
        &host.user
    };
    let pid = if docker || host.pid.is_empty() {
        "/run/nginx.pid"
    } else {
        &host.pid
    };
    c.push_str(&format!(
        "user {user};\nworker_processes {};\npid {pid};\nerror_log /var/log/nginx/error.log warn;\nworker_rlimit_nofile {};\n",
        settings.worker_processes.trim(),
        (settings.worker_connections * 2).max(8192)
    ));
    if !docker && host.include_modules {
        c.push_str("include /etc/nginx/modules-enabled/*.conf;\n");
    }
    if !settings.custom_main.trim().is_empty() {
        c.push_str("\n# custom main context\n");
        c.push_str(settings.custom_main.trim_end());
        c.push('\n');
    }
    c.push_str(&format!(
        "\nevents {{\n    worker_connections {};\n    multi_accept on;\n}}\n\nhttp {{\n",
        settings.worker_connections
    ));
    let mut h = String::new();
    h.push_str("include /etc/nginx/mime.types;\ndefault_type application/octet-stream;\n\n");
    h.push_str(
        "log_format asc '$remote_addr - $remote_user [$time_local] \"$request\" $status '\n           \
         '$body_bytes_sent \"$http_referer\" \"$http_user_agent\" host=$host '\n           \
         'rt=$request_time urt=$upstream_response_time';\n",
    );
    if settings.access_log {
        h.push_str("access_log /var/log/nginx/access.log asc;\n\n");
    } else {
        h.push_str("access_log off;\n\n");
    }
    h.push_str(&format!(
        "sendfile on;\ntcp_nopush on;\nkeepalive_timeout {};\ntypes_hash_max_size 2048;\n\
         server_names_hash_bucket_size 128;\nserver_names_hash_max_size 4096;\n\
         client_max_body_size {};\nserver_tokens {};\n\n",
        settings.keepalive_timeout,
        settings.client_max_body_size.trim(),
        if settings.server_tokens { "on" } else { "off" }
    ));
    if settings.gzip {
        h.push_str(&format!(
            "gzip on;\ngzip_vary on;\ngzip_proxied any;\ngzip_comp_level {};\ngzip_min_length 256;\n\
             gzip_types text/plain text/css text/xml text/javascript application/javascript \
             application/json application/xml application/rss+xml application/wasm image/svg+xml;\n\n",
            settings.gzip_level
        ));
    }
    h.push_str(&format!(
        "ssl_protocols {};\nssl_prefer_server_ciphers off;\nssl_session_cache shared:ASC_SSL:10m;\n\
         ssl_session_timeout 1d;\nssl_session_tickets off;\n\n",
        settings.tls_protocols.join(" ")
    ));
    h.push_str(
        "# WebSocket upgrade; an empty Connection keeps upstream keepalive working.\n\
         map $http_upgrade $connection_upgrade {\n    default upgrade;\n    '' '';\n}\n\n",
    );
    if settings.cloudflare_real_ip {
        h.push_str(&format!("include {};\n", p(base, CLOUDFLARE)));
    }
    h.push_str(&format!("include {};\n", p(base, CUSTOM_HTTP)));
    if !docker && host.include_conf_d {
        h.push_str("include /etc/nginx/conf.d/*.conf;\n");
    }
    if !docker && host.include_sites_enabled {
        h.push_str("include /etc/nginx/sites-enabled/*;\n");
    }
    h.push('\n');
    let v6 = features.ipv6;
    if docker || !host.foreign_default_http {
        h.push_str(
            "# Unknown names: ACME challenges only.\nserver {\n    listen 80 default_server;\n",
        );
        if v6 {
            h.push_str("    listen [::]:80 default_server;\n");
        }
        h.push_str(&format!(
            "    server_name _;\n    include {};\n    location / {{\n        return 444;\n    }}\n}}\n\n",
            p(base, ACME_SNIPPET)
        ));
    }
    if features.reject_handshake && (docker || !host.foreign_default_https) {
        h.push_str("server {\n    listen 443 ssl default_server;\n");
        if v6 {
            h.push_str("    listen [::]:443 ssl default_server;\n");
        }
        h.push_str("    server_name _;\n    ssl_reject_handshake on;\n}\n\n");
    }
    h.push_str(&format!(
        "include {};\n",
        base.join("sites").join("*.conf").display()
    ));
    c.push_str(&indent(&h, "    "));
    c.push_str("\n}\n");
    files.insert(PathBuf::from(NGINX_CONF), c);

    files.insert(
        PathBuf::from(CUSTOM_HTTP),
        format!(
            "# Custom http-context directives (asc web settings: custom_http).\n{}\n",
            settings.custom_http.trim_end()
        ),
    );
    files.insert(PathBuf::from(CLOUDFLARE), cloudflare.directives());
    files.insert(
        PathBuf::from(ACME_SNIPPET),
        format!(
            "# ACME HTTP-01 challenges, answered from the daemon's webroot.\n\
             location ^~ /.well-known/acme-challenge/ {{\n    root {};\n    default_type text/plain;\n    try_files $uri =404;\n}}\n",
            paths.webroot.display()
        ),
    );
    files.insert(
        PathBuf::from(PROXY_SNIPPET),
        "proxy_http_version 1.1;\n\
         proxy_set_header X-Real-IP $remote_addr;\n\
         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n\
         proxy_set_header X-Forwarded-Proto $scheme;\n\
         proxy_set_header X-Forwarded-Host $host;\n\
         proxy_set_header X-Forwarded-Port $server_port;\n"
            .to_string(),
    );
    files
}

/// `asc_<id>_<hash>`: `.`/`-` are not allowed in every nginx variable
/// context, and the hash keeps `a-b` and `a_b` apart.
pub fn upstream_name(id: &str) -> String {
    let mut hash: u32 = 0x811c_9dc5;
    for b in id.bytes() {
        hash ^= u32::from(b);
        hash = hash.wrapping_mul(0x0100_0193);
    }
    let clean: String = id
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
        .collect();
    format!("asc_{clean}_{hash:08x}")
}

/// One site's file. `global_real_ip` — Cloudflare is already trusted at the
/// http level, so the site does not include the ranges a second time.
pub fn render_site(
    resolved: &Resolved<'_>,
    settings: &Settings,
    features: Features,
    base: &Path,
) -> String {
    let site = resolved.site;
    let mut out = format!(
        "# asc-daemon site {} ({}).\n{}",
        site.id,
        site.managed_by.as_deref().unwrap_or("local"),
        HEADER
    );
    if let Some(raw) = &site.raw_config {
        out.push_str("# Raw configuration supplied by the operator.\n");
        out.push_str(raw.trim_end());
        out.push('\n');
        return out;
    }

    let name = upstream_name(&site.id);
    let up = &site.upstream;
    out.push_str(&format!("upstream {name} {{\n"));
    match up.balance {
        Balance::RoundRobin => {}
        Balance::LeastConn => out.push_str("    least_conn;\n"),
        Balance::IpHash => out.push_str("    ip_hash;\n"),
        Balance::Hash => out.push_str(&format!("    hash {} consistent;\n", up.hash_key.trim())),
    }
    for (index, (server, address)) in up.servers.iter().zip(&resolved.addresses).enumerate() {
        let mut line = format!("    server {address}");
        if server.weight > 1 {
            line.push_str(&format!(" weight={}", server.weight));
        }
        if server.max_fails > 0 {
            line.push_str(&format!(" max_fails={}", server.max_fails));
        }
        if server.fail_timeout_secs > 0 {
            line.push_str(&format!(" fail_timeout={}s", server.fail_timeout_secs));
        }
        // The hash methods do not allow backup servers; nginx -t would say
        // so, but dropping the flag is kinder than failing the site.
        if server.backup && matches!(up.balance, Balance::RoundRobin | Balance::LeastConn) {
            line.push_str(" backup");
        }
        if server.down || resolved.down.get(index).copied().unwrap_or(false) {
            line.push_str(" down");
        }
        line.push_str(";\n");
        out.push_str(&line);
    }
    if up.keepalive > 0 {
        out.push_str(&format!("    keepalive {};\n", up.keepalive));
    }
    out.push_str("}\n\n");

    let names = site.server_names.join(" ");
    let v6 = features.ipv6;
    let https = resolved.cert.is_some();

    // :80 — ACME challenges always; the app itself unless HTTPS redirects.
    out.push_str("server {\n    listen 80;\n");
    if v6 {
        out.push_str("    listen [::]:80;\n");
    }
    out.push_str(&format!(
        "    server_name {names};\n    include {};\n",
        p(base, ACME_SNIPPET)
    ));
    if https && site.tls.redirect_http {
        out.push_str(
            "\n    location / {\n        return 301 https://$host$request_uri;\n    }\n}\n",
        );
    } else {
        out.push_str(&proxy_body(site, settings, &name, false, base));
        out.push_str("}\n");
    }

    if let Some((cert, key)) = &resolved.cert {
        let http2 = site.tls.http2 && settings.http2;
        let h2_listen = if http2 && !features.http2_directive {
            " http2"
        } else {
            ""
        };
        out.push_str(&format!("\nserver {{\n    listen 443 ssl{h2_listen};\n"));
        if v6 {
            out.push_str(&format!("    listen [::]:443 ssl{h2_listen};\n"));
        }
        if http2 && features.http2_directive {
            out.push_str("    http2 on;\n");
        }
        out.push_str(&format!(
            "    server_name {names};\n    ssl_certificate {};\n    ssl_certificate_key {};\n",
            cert.display(),
            key.display()
        ));
        out.push_str(&proxy_body(site, settings, &name, true, base));
        out.push_str("}\n");
    }
    out
}

fn proxy_body(
    site: &Site,
    settings: &Settings,
    upstream: &str,
    https: bool,
    base: &Path,
) -> String {
    let mut b = String::new();
    if site.real_ip == RealIp::Cloudflare && !settings.cloudflare_real_ip {
        b.push_str(&format!("    include {};\n", p(base, CLOUDFLARE)));
    }
    if !site.proxy.client_max_body_size.is_empty() {
        b.push_str(&format!(
            "    client_max_body_size {};\n",
            site.proxy.client_max_body_size.trim()
        ));
    }
    if !site.extra_server.trim().is_empty() {
        b.push_str("\n    # extra_server\n");
        b.push_str(&indent(site.extra_server.trim_end(), "    "));
        b.push('\n');
    }
    let scheme = if site.upstream.tls { "https" } else { "http" };
    b.push_str(&format!(
        "\n    location / {{\n        proxy_pass {scheme}://{upstream};\n        include {};\n",
        p(base, PROXY_SNIPPET)
    ));
    if site.proxy.upstream_host {
        b.push_str("        proxy_set_header Host $proxy_host;\n");
    } else {
        b.push_str("        proxy_set_header Host $host;\n");
    }
    if site.upstream.tls {
        b.push_str("        proxy_ssl_server_name on;\n");
    }
    if site.proxy.websocket {
        b.push_str(
            "        proxy_set_header Upgrade $http_upgrade;\n        proxy_set_header Connection $connection_upgrade;\n",
        );
    } else {
        b.push_str("        proxy_set_header Connection \"\";\n");
    }
    for (directive, value) in [
        ("proxy_connect_timeout", site.proxy.connect_timeout_secs),
        ("proxy_read_timeout", site.proxy.read_timeout_secs),
        ("proxy_send_timeout", site.proxy.send_timeout_secs),
    ] {
        if value > 0 {
            b.push_str(&format!("        {directive} {value}s;\n"));
        }
    }
    if site.proxy.no_buffering {
        b.push_str("        proxy_buffering off;\n        proxy_request_buffering off;\n");
    }
    for header in &site.proxy.request_headers {
        b.push_str(&format!(
            "        proxy_set_header {} \"{}\";\n",
            header.name, header.value
        ));
    }
    // add_header in a location replaces every inherited one, so HSTS lives
    // here next to the operator's own response headers.
    if https && (site.tls.hsts || settings.hsts) {
        b.push_str("        add_header Strict-Transport-Security \"max-age=63072000\" always;\n");
    }
    for header in &site.proxy.response_headers {
        b.push_str(&format!(
            "        add_header {} \"{}\" always;\n",
            header.name, header.value
        ));
    }
    if !site.extra_location.trim().is_empty() {
        b.push_str("\n        # extra_location\n");
        b.push_str(&indent(site.extra_location.trim_end(), "        "));
        b.push('\n');
    }
    b.push_str("    }\n");
    b
}

#[cfg(test)]
mod tests {
    use super::super::model::*;
    use super::*;

    fn paths() -> Paths {
        Paths {
            root: "/etc/asc/webserver".into(),
            state: "/var/lib/asc/webserver".into(),
            webroot: "/var/www/asc-acme".into(),
        }
    }

    fn modern() -> Features {
        Features::for_version(Some("1.28.0"), true)
    }

    fn site() -> Site {
        Site {
            id: "grafana".into(),
            server_names: vec!["grafana.example.com".into()],
            managed_by: Some("platform".into()),
            disabled: false,
            upstream: Upstream {
                servers: vec![UpstreamServer {
                    target: Target::App {
                        app: "grafana".into(),
                        port: 3000,
                    },
                    weight: 1,
                    backup: false,
                    max_fails: 0,
                    fail_timeout_secs: 0,
                    down: false,
                }],
                ..Default::default()
            },
            tls: Tls {
                mode: TlsMode::Acme,
                redirect_http: true,
                hsts: true,
                http2: true,
                ..Default::default()
            },
            proxy: Proxy {
                websocket: true,
                ..Default::default()
            },
            real_ip: RealIp::Cloudflare,
            extra_server: String::new(),
            extra_location: String::new(),
            raw_config: None,
        }
    }

    #[test]
    fn versions() {
        assert_eq!(parse_version("1.25.1"), Some((1, 25, 1)));
        assert_eq!(parse_version("1.18"), Some((1, 18, 0)));
        let old = Features::for_version(Some("1.18.0"), false);
        assert!(!old.http2_directive && !old.reject_handshake);
        assert!(modern().http2_directive && modern().reject_handshake);
    }

    #[test]
    fn http_only_until_the_certificate_exists() {
        let s = site();
        let r = Resolved {
            site: &s,
            addresses: vec!["127.0.0.1:32768".into()],
            cert: None,
            down: vec![],
        };
        let out = render_site(&r, &Settings::default(), modern(), Path::new("/b"));
        assert!(out.contains("server 127.0.0.1:32768;"));
        assert!(out.contains("include /b/snippets/acme.conf;"));
        assert!(!out.contains("listen 443"));
        assert!(!out.contains("return 301"));
        assert!(out.contains("proxy_pass http://asc_grafana_"));
        assert!(out.contains("include /b/snippets/cloudflare-realip.conf;"));
    }

    #[test]
    fn https_redirects_and_uses_http2_directive() {
        let s = site();
        let r = Resolved {
            site: &s,
            addresses: vec!["127.0.0.1:32768".into()],
            cert: Some(("/c/fullchain.pem".into(), "/c/privkey.pem".into())),
            down: vec![],
        };
        let out = render_site(&r, &Settings::default(), modern(), Path::new("/b"));
        assert!(out.contains("return 301 https://$host$request_uri;"));
        assert!(out.contains("listen 443 ssl;\n    listen [::]:443 ssl;\n    http2 on;"));
        assert!(out.contains("ssl_certificate /c/fullchain.pem;"));
        assert!(out.contains("Strict-Transport-Security"));
        assert!(out.contains("proxy_set_header Connection $connection_upgrade;"));

        let old = Features::for_version(Some("1.24.0"), false);
        let out = render_site(&r, &Settings::default(), old, Path::new("/b"));
        assert!(out.contains("listen 443 ssl http2;"));
        assert!(!out.contains("[::]"));
    }

    #[test]
    fn global_cloudflare_is_not_repeated_per_site() {
        let s = site();
        let settings = Settings {
            cloudflare_real_ip: true,
            ..Default::default()
        };
        let r = Resolved {
            site: &s,
            addresses: vec!["127.0.0.1:1".into()],
            cert: None,
            down: vec![],
        };
        let out = render_site(&r, &settings, modern(), Path::new("/b"));
        assert!(!out.contains("cloudflare-realip"));
        let files = render_global(
            &settings,
            modern(),
            &Ranges::embedded(),
            &paths(),
            Path::new("/b"),
            true,
        );
        assert!(
            files[Path::new(NGINX_CONF)].contains("include /b/snippets/cloudflare-realip.conf;")
        );
    }

    #[test]
    fn upstream_options() {
        let mut s = site();
        s.upstream.balance = Balance::IpHash;
        s.upstream.keepalive = 16;
        s.upstream.servers[0].backup = true;
        s.upstream.servers.push(UpstreamServer {
            target: Target::Address {
                address: "10.0.0.2:3000".into(),
            },
            weight: 5,
            backup: false,
            max_fails: 3,
            fail_timeout_secs: 10,
            down: true,
        });
        let r = Resolved {
            site: &s,
            addresses: vec!["127.0.0.1:1".into(), "10.0.0.2:3000".into()],
            cert: None,
            down: vec![],
        };
        let out = render_site(&r, &Settings::default(), modern(), Path::new("/b"));
        assert!(out.contains("    ip_hash;\n"));
        assert!(
            out.contains("server 127.0.0.1:1;\n"),
            "backup dropped under ip_hash"
        );
        assert!(out.contains("server 10.0.0.2:3000 weight=5 max_fails=3 fail_timeout=10s down;"));
        assert!(out.contains("keepalive 16;"));
    }

    #[test]
    fn raw_config_is_verbatim() {
        let mut s = site();
        s.raw_config = Some("server { listen 80; }".into());
        let r = Resolved {
            site: &s,
            addresses: vec![],
            cert: None,
            down: vec![],
        };
        let out = render_site(&r, &Settings::default(), modern(), Path::new("/b"));
        assert!(out.ends_with("server { listen 80; }\n"));
        assert!(!out.contains("upstream"));
    }

    #[test]
    fn global_system_profile_keeps_host_includes() {
        let settings = Settings {
            host: HostProfile {
                user: "www-data".into(),
                pid: "/run/nginx.pid".into(),
                include_modules: true,
                include_conf_d: true,
                include_sites_enabled: true,
                foreign_default_http: true,
                ..Default::default()
            },
            ..Default::default()
        };
        let files = render_global(
            &settings,
            modern(),
            &Ranges::embedded(),
            &paths(),
            Path::new("/b"),
            false,
        );
        let conf = &files[Path::new(NGINX_CONF)];
        assert!(conf.contains("user www-data;"));
        assert!(conf.contains("include /etc/nginx/modules-enabled/*.conf;"));
        assert!(conf.contains("include /etc/nginx/sites-enabled/*;"));
        assert!(!conf.contains("listen 80 default_server"));
        assert!(conf.contains("ssl_reject_handshake on;"));
        assert!(conf.contains("include /b/sites/*.conf;"));
        assert!(files[Path::new(ACME_SNIPPET)].contains("root /var/www/asc-acme;"));
    }

    /// Writes a representative configuration tree to `$ASC_RENDER_DIR` so it
    /// can be checked by a real `nginx -t` (see docs/english/webserver.md):
    /// `docker run --rm -v $D:$D nginx:stable-alpine nginx -t -c $D/nginx.conf`.
    #[test]
    #[ignore = "writes files for a manual nginx -t run"]
    fn write_fixture_tree() {
        let Ok(dir) = std::env::var("ASC_RENDER_DIR") else {
            return;
        };
        let base = PathBuf::from(&dir);
        let paths = Paths {
            root: base.clone(),
            state: base.join("state"),
            webroot: base.join("www"),
        };
        let settings = Settings {
            custom_http: "# operator snippet\nproxy_headers_hash_max_size 1024;".into(),
            ..Default::default()
        };
        let features = Features::for_version(Some("1.28.0"), false);
        let mut files = render_global(
            &settings,
            features,
            &Ranges::embedded(),
            &paths,
            &base,
            true,
        );

        let key = rcgen::KeyPair::generate().unwrap();
        let cert = rcgen::CertificateParams::new(vec!["tls.example.com".to_string()])
            .unwrap()
            .self_signed(&key)
            .unwrap();
        let (c, k) = provided_cert_files("tls");
        files.insert(c.clone(), cert.pem());
        files.insert(k.clone(), key.serialize_pem());

        let plain = site();
        let mut tls = site();
        tls.id = "tls".into();
        tls.server_names = vec!["tls.example.com".into()];
        tls.proxy.request_headers.push(Header {
            name: "X-Asc".into(),
            value: "1".into(),
        });
        tls.proxy.response_headers.push(Header {
            name: "X-Frame-Options".into(),
            value: "DENY".into(),
        });
        tls.proxy.no_buffering = true;
        tls.proxy.client_max_body_size = "2g".into();
        tls.extra_location = "proxy_cache_bypass $http_upgrade;".into();
        let mut balanced = site();
        balanced.id = "lb.example".into();
        balanced.server_names = vec!["lb.example.com".into()];
        balanced.upstream.balance = Balance::Hash;
        balanced.upstream.hash_key = "$cookie_session".into();
        balanced.upstream.keepalive = 32;
        balanced.upstream.servers.push(UpstreamServer {
            target: Target::Address {
                address: "10.0.0.2:3000".into(),
            },
            weight: 3,
            backup: true,
            max_fails: 2,
            fail_timeout_secs: 5,
            down: false,
        });
        let sites = [
            Resolved {
                site: &plain,
                addresses: vec!["127.0.0.1:3000".into()],
                cert: None,
                down: vec![],
            },
            Resolved {
                site: &tls,
                addresses: vec!["127.0.0.1:3001".into()],
                cert: Some((base.join(&c), base.join(&k))),
                down: vec![],
            },
            Resolved {
                site: &balanced,
                addresses: vec!["127.0.0.1:3002".into(), "10.0.0.2:3000".into()],
                cert: None,
                down: vec![],
            },
        ];
        for resolved in &sites {
            files.insert(
                site_file(&resolved.site.id),
                render_site(resolved, &settings, features, &base),
            );
        }
        for (rel, content) in files {
            let path = base.join(rel);
            std::fs::create_dir_all(path.parent().unwrap()).unwrap();
            std::fs::write(path, content).unwrap();
        }
    }

    #[test]
    fn upstream_names_are_distinct() {
        assert_ne!(upstream_name("a-b"), upstream_name("a_b"));
        assert!(upstream_name("x.y").starts_with("asc_x_y_"));
    }
}
