blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/AdminServiceCloud/asc-daemon/discussions
    about: Ask questions and join discussions
  - name: 📚 Documentation
    url: https://github.com/AdminServiceCloud/asc-daemon/tree/main/docs
    about: Explore the project documentation
