//! Daemon modules. Future subsystems (tunnel, mcp, sftp, db) get their own
//! submodules here.

pub mod api;
pub mod apps;
pub mod backup;
pub mod client;
pub mod compose;
pub mod config;
pub mod console;
pub mod docker;
pub mod exec;
pub mod fail2ban;
pub mod files;
pub mod firewall;
pub mod http;
pub mod i18n;
pub mod logging;
pub mod mcp;
pub mod monitor;
pub mod pkg;
pub mod platform;
pub mod progress;
pub mod scheduler;
pub mod server;
pub mod service;
pub mod users;
pub mod webserver;
pub mod wireguard;
